### ISSUE TITLE
Full usage example?

### ISSUE THREAD

**Issue by baohx2000** [bloodyowl/react-translate#1]
Is there an actual example of using your library anywhere?
I like the methodology but I'd like an example of how you'd store the individual translation files.

**Comment by bloodyowl** [comment]
I set up an example app there: https://github.com/bloodyowl/react-translate-example

**Comment by baohx2000** [comment]
thank you!  `export default translate("Title")(Title)` looks like it may be the missing piece of the puzzle since I'm not yet using classes everywhere.
