### ISSUE TITLE
Issue with Gatsbyjs when building (server side)

### ISSUE THREAD

**Issue by mtt87** [bloodyowl/react-translate#10]
Hi, I'm having issue with Gatsbyjs (static generator).

The library works fine when in `develop` mode, which means that it's running in the browser, but when I try to build the project, which means that the code is rendered server side to produce static content, it's not working.

https://github.com/gatsbyjs/gatsby/issues/688#issue-209287346

Seems to be related to the `context` which, if I understand correctly, is responsible to pass the `TranslatorProvider` down to the child components of the app.

```
Failed at generating HTML

/Users/mattia/Dev/meal/website2/node_modules/gatsby/dist/bin/cli.js:42
      throw err;
      ^
Error: TypeError: translator is not a function
    at Translator.render (render-page.js:36896:18)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:14352:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:14375:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:13915:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:13811:22)
    at Object.mountComponent (render-page.js:6882:36)
    at ReactDOMComponent.mountChildren (render-page.js:12945:45)
    at ReactDOMComponent._createContentMarkup (render-page.js:9972:33)
    at ReactDOMComponent.mountComponent (render-page.js:9839:30)
    at Object.mountComponent (render-page.js:6882:36)
```

Quick question: is this library supposed to work server-side or only browser-side?

Thank you

**Comment by bloodyowl** [comment]
Hi, 

Yes, it's supposed to work on the server too. Do you have a minimal repro?

**Comment by mtt87** [comment]
😄 Yes `npm i -g gatsby` then `gatsby new test-site` then `cd test-site`

create `gatsby-browser.js`
```
import React from 'react';
import { TranslatorProvider } from "react-translate";
const translations = require('./i18n');

exports.wrapRootComponent = (Root) => {
  const Wrapper = () => (
    <TranslatorProvider translations={translations}>
      <Root />
    </TranslatorProvider>
  )
  return Wrapper;
}
```

create `pages/home.js`
```
import React from 'react';
const Home = ({ t }) => {
  return (
    <div>
      {t("tagline1")}
    </div>
  );
}
export default translate("Home")(Home);
```

then if you run `gatsby develop` and open your browser on `localhost:8000/home` everything should work fine
as soon as you run `gatsby build` the problem is that the context is lost and the `translate('component')(component)` doesn't work anymore, probably because there is no more ancestor `<TranslatorProvider>`

**Comment by mtt87** [comment]
https://github.com/gatsbyjs/gatsby/issues/688#issuecomment-281969669

Do you think it could it be related to this step?
https://github.com/gatsbyjs/gatsby/blob/b4d585a2c0035dc3c8896c42e2daaac1b520be5a/lib/utils/webpack.config.js#L137

```
case 'build-html':
  config.plugin('static-site-generator', StaticSiteGeneratorPlugin, ['render-page.js', routes])
```

Seems like you are adding manually routes to`render-page.js` otherwise it doesn't inherit them automatically from the `context` of `react-router`?

I was thinking if I have to do the same and pass the `translator` function created by the provider but at the moment I have no clear idea how all of this is working.

Could be related to the `scope` of `static-site-generator-webpack`?
https://github.com/markdalgleish/static-site-generator-webpack-plugin#scope

At this point I don't think it's related to your package because I get same error when using `react-intl`.

But if you wanna be nice and helpful I appreciate any hint to fix this.

**Comment by mtt87** [comment]
Almost solved
https://github.com/gatsbyjs/gatsby/issues/688#issuecomment-282138939

Not related to your library, I close the issue.

Thank you 😄
