### ISSUE TITLE
PropTypes is undefined

### ISSUE THREAD

**Issue by tspoke** [bloodyowl/react-translate#14]
PropTypes is deprecated. Your package cannot be used with recent version of react (crash).

How to fix : 

- Remove import from `react` package
- Add `prop-types` package and replace all imports by this one

**Comment by bloodyowl** [comment]
Fixed and published as 6.0.0 https://github.com/bloodyowl/react-translate/commit/76b9a0bad976e91a4cc0b9a1d3d36cabd7f3fe88
