### ISSUE TITLE
Locale identification and usage

### ISSUE THREAD

**Issue by marudy** [bloodyowl/react-translate#17]
Hi @bloodyowl 

and thanks for the simple library you have provided.

I would like to ask how do you compose multiple locale objects into the `translations` one?

i.e. if I have:
* **en:**
```
export default {
  locale: 'en',
  Home: {
    HELLO: 'Hello world'
  }
}
```
* **fr:**

```
export default {
  locale: 'fr',
  Home: {
    HELLO: 'Bonjour le monde'
  }
}
```
what should be the structure of `translations`?

**Comment by marudy** [comment]
Hi there,

any quick feedback on this one?

**Comment by bloodyowl** [comment]
can you explain a bit more what you want? I don’t understand your question here

_
mlb

**Comment by marudy** [comment]
Hi there,

thanks for replying.

I want to setup multiple languages. How should I struct the `translations` object? The README example shows a setup that contains only 1 language.

**Comment by bloodyowl** [comment]
the `translations` object represents the translations **in a given language**.
react-translate doesn't make any assumption on how you provide different `translations` set.

you can for instance use dynamic imports, let your bundler handle it or load it with fetch or XMLHttpRequest.

as an example:

```js
let availableLanguages = ["fr", "en"];
let defaultLanguage = "en";

let getLanguage = availableLanguages.includes(item => item === window.navigator.language)
  ? window.navigator.language
  : defaultLanguage;

import(`./translations/${getLanguage()}.js`).then(translations => initApplication(translations))
```

**Comment by marudy** [comment]
Thanks for clarifying that! Since you wrote the example here, I propose you should add it at your readme file as well :smile:
